services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=healthcare-app-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=healthcare-user'
    ports:
      - '5432:5432'
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped
  envoy-grpc-to-json:
    image: envoyproxy/envoy:v1.21.0
    volumes:
      - ./envoy_grpc_to_json.yaml:/etc/envoy/envoy_grpc_to_json.yaml
      - ./appointment.pb:/data/appointment.pb
      - .:/data
    ports:
      - "9099:9099"
      - "8089:8089"
    command: [ "envoy", "-c", "/etc/envoy/envoy_grpc_to_json.yaml", "--log-level", "debug" ]
  envoy-grpcweb:
    image: envoyproxy/envoy:v1.21.0
    volumes:
      - ./envoy_d_grpcweb.yaml:/etc/envoy/envoy_d_grpcweb.yaml
      - ./appointment.pb:/data/appointment.pb
      - .:/data
    ports:
      - "9199:9199"
      - "8099:8099"
    command: [ "envoy", "-c", "/etc/envoy/envoy_d_grpcweb.yaml", "--log-level", "debug" ]
